site_name: ReactiveProperty documentation
pages:
- Home: 'index.md'
- Getting started:
    - 'Windows Presentation Foundation': 'getting-started/wpf.md'
    - 'Universal Windows Platform': 'getting-started/uwp.md'
    - 'Xamarin.Forms': 'getting-started/xf.md'
- Features:
    - 'ReactiveProperty': 'features/ReactiveProperty.md'
    - 'Commanding': 'features/Commanding.md'
    - 'Collections': 'features/Collections.md'
    - 'Work together with plane model layer objects': 'features/Work-together-with-plane-model-layer-objects.md'
    - 'Useful classes which implement IObservable': 'features/Notifiers.md'
    - 'Extension methods': 'features/Extension-methods.md'
    - 'Transfer event to ViewModel from View': 'features/Event-transfer-to-ViewModel-from-View.md'
theme: readthedocs
